name: Prerelease on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"
jobs:
  release-please:
    runs-on: ubuntu-20.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: react-package-template
